questions = [
    {
        topic: "chemistry",
        question: "How many covalent bonds can carbon form?",
        optionA: { answer: 1, result: 0 },
        optionB: { answer: 2, result: 0 },
        optionC: { answer: 3, result: 0 },
        optionD: { answer: 4, result: 1 },
    },
    {
        topic: "politics",
        question: "When was Donald Trump elected?",
        optionA: { answer: 2012, result: 0 },
        optionB: { answer: 2015, result: 0 },
        optionC: { answer: 2016, result: 1 },
        optionD: { answer: 2019, result: 0 },
    },
    {
        topic: "biology",
        question: "Which direction does DNA read?",
        optionA: { answer: "3'->5'", result: 1 },
        optionB: { answer: "5'->3'", result: 0 },
        optionC: { answer: "none of the above", result: 0 },
        optionD: { answer: "all of the above", result: 0 },
    },
    {
        topic: "physics",
        question: "Potential energy is best described by which equation?",
        optionA: { answer: "P = nRT", result: 0 },
        optionB: { answer: "F = ma", result: 0 },
        optionC: { answer: "S = 1/2(v**2)", result: 0 },
        optionD: { answer: "U = mgh", result: 1 },
    },
    {
        topic: "history",
        question: "How did World War I start",
        optionA: { answer: "Hitler", result: 0 },
        optionB: { answer: "The French surrendered", result: 0 },
        optionC: { answer: "Someone shot Franz Ferdinand", result: 1 },
        optionD: { answer: "Austria-Hungary declared war on France", result: 0 },
    },
    {
        topic: "Biology",
        question: "Packages proteins to their desired destination",
        optionA: { answer: "Golgi Body", result: 1 },
        optionB: { answer: "Smooth Endoplasmic Reticulum", result: 0 },
        optionC: { answer: "Nucleus", result: 0 },
        optionD: { answer: "Mitochondria", result: 0 },
    },
    {
        topic: "Computer Science",
        question: "Binary search is known to have a run-time complexity of",
        optionA: { answer: "N log N", result: 1 },
        optionB: { answer: "N", result: 0 },
        optionC: { answer: "N**2", result: 0 },
        optionD: { answer: "C", result: 0 },
    },
    {
        topic: "Chemistry",
        question: "Halogens are most attracted to which of the following",
        optionA: { answer: "alkali metals", result: 1 },
        optionB: { answer: "alkali earth metals", result: 0 },
        optionC: { answer: "transition metals", result: 0 },
        optionD: { answer: "nobel gases", result: 0 },
    },
    {
        topic: "Biology",
        question: "DNA bases are held together by",
        optionA: { answer: "Phosphodiester bonds", result: 0 },
        optionB: { answer: "Electorstatic forces", result: 0 },
        optionC: { answer: "Non-polar interactions", result: 0 },
        optionD: { answer: "Hydrogen Bonds", result: 1 },
    },
    {
        topic: "Chemistry",
        question: "Group 16 on the periodic table is most attracted to which of the following",
        optionA: { answer: "alkali metals", result: 0 },
        optionB: { answer: "alkali earth metals", result: 1 },
        optionC: { answer: "transition metals", result: 0 },
        optionD: { answer: "nobel gases", result: 0 },
    },
    {
        topic: "Computer Science",
        question: "simple search is known to have a run-time complexity of",
        optionA: { answer: "N log N", result: 0 },
        optionB: { answer: "N", result: 1 },
        optionC: { answer: "N**2", result: 0 },
        optionD: { answer: "C", result: 0 },
    },
    {
        topic: "Computer Science",
        question: "Bubble sort is known to have a run-time complexity of",
        optionA: { answer: "N log N", result: 0 },
        optionB: { answer: "N", result: 0 },
        optionC: { answer: "N**2", result: 1 },
        optionD: { answer: "C", result: 0 },
    },
    {
        topic: "Computer Science",
        question: "merge sort is known to have a run-time complexity of",
        optionA: { answer: "N log N", result: 1 },
        optionB: { answer: "N", result: 0 },
        optionC: { answer: "N**2", result: 0 },
        optionD: { answer: "C", result: 0 },
    },
    {
        topic: "history",
        question: "How did World War II start",
        optionA: { answer: "Hitler", result: 1 },
        optionB: { answer: "The French surrendered", result: 0 },
        optionC: { answer: "Someone shot Franz Ferdinand", result: 0 },
        optionD: { answer: "Austria-Hungary declared war on France", result: 0 },
    },
    {
        topic: "politics",
        question: "When was Barack Obama elected?",
        optionA: { answer: 2006, result: 0 },
        optionB: { answer: 2008, result: 1 },
        optionC: { answer: 2012, result: 0 },
        optionD: { answer: 2016, result: 0 },
    },
    {
        topic: "biology",
        question: "Which direction does mRNA built?",
        optionA: { answer: "3'->5'", result: 0 },
        optionB: { answer: "5'->3'", result: 1 },
        optionC: { answer: "none of the above", result: 0 },
        optionD: { answer: "all of the above", result: 0 },
    },
    {
        topic: "chemistry",
        question: "How many covalent bonds does oxygen prefer?",
        optionA: { answer: 1, result: 0 },
        optionB: { answer: 2, result: 1 },
        optionC: { answer: 3, result: 0 },
        optionD: { answer: 4, result: 0 },
    },
    {
        topic: "physics",
        question: "Kinetic energy is best described by which of the following?",
        optionA: { answer: "K = mv/2", result: 0 },
        optionB: { answer: "K = mv**2", result: 1 },
        optionC: { answer: "K = 1/2(v**2)", result: 0 },
        optionD: { answer: "K = v*d", result: 0 },
    },
    {
        topic: "physics",
        question: "What is terminal velocity?",
        optionA: { answer: "The highest speed an object reaches because of unbalanced forces", result: 1 },
        optionB: { answer: "When an object reaches its final velocity of zero", result: 0 },
        optionC: { answer: "The highest speed an object reaches because air resistance offsets gravity in the real world", result: 0 },
        optionD: { answer: "V = v0 + at", result: 0 },
    },
    {
        topic: "physics",
        question: "What is the buoyant force?",
        optionA: { answer: "The left or right overall force that an underwater object feels.", result: 0 },
        optionB: { answer: "The downwards overall force that an underwater object feels.", result: 0 },
        optionC: { answer: "The upwards overall force that an underwater object feels.", result: 1 },
        optionD: { answer: "The upwards overall force that an object on the surface of water feels.", result: 0 },
    },
    {
        topic: "chemistry",
        question: "If a reaction gives off heat, it is referred to as",
        optionA: { answer: "endothelial", result: 0 },
        optionB: { answer: "exothermic'", result: 1 },
        optionC: { answer: "endothermic", result: 0 },
        optionD: { answer: "exergonic", result: 0 },
    },
    {
        topic: "chemistry",
        question: "a reaction that is spontaneous is said to be",
        optionA: { answer: "endergonic", result: 0 },
        optionB: { answer: "exothermic'", result: 0 },
        optionC: { answer: "endothermic", result: 0 },
        optionD: { answer: "exergonic", result: 1 },
    },
]

module.exports = {
    read: function () {
        return questions
    }
}